dhcp:
  status:
    cmd: systemctl status isc-dhcp-server
    help: Display the status of the DHCP server
  start:
    cmd: systemctl start isc-dhcp-server
    help: Start the DHCP server
  stop:
    cmd: systemctl stop isc-dhcp-server
    help: Stop the DHCP server
server:
  slides:
    cmd: /home/pi/srv/slides/slides.v/bin/python -m slides
    help: Start the slides server (non-daemon mode)
